
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Speakeasy.Models.Operations
{
    using Speakeasy.Models.Shared;
    using Speakeasy.Utils;
    
    public class ListDrinksRequest
    {

        /// <summary>
        /// The type of drink to filter by. If not provided all drinks will be returned.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=drinkType")]
        public DrinkType? DrinkType { get; set; }
    }
}