
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SpeakeasyBar.Models.Webhooks
{
    using Newtonsoft.Json;
    using SpeakeasyBar.Models.Components;
    
    public class StockUpdateRequestBody
    {

        [JsonProperty("drink")]
        public DrinkInput? Drink { get; set; }

        [JsonProperty("ingredient")]
        public IngredientInput? Ingredient { get; set; }
    }
}