
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Speakeasy.Bar.Models.Requests
{
    using Speakeasy.Bar.Models.Components;
    using System.Net.Http;
    using System;
    
    public class AuthenticateResponse
    {

        /// <summary>
        /// An error occurred interacting with the API.
        /// </summary>
        public APIError? APIError { get; set; }

        /// <summary>
        /// HTTP response content type for this operation
        /// </summary>
        public string? ContentType { get; set; } = default!;

        /// <summary>
        /// An unknown error occurred interacting with the API.
        /// </summary>
        public Error? Error { get; set; }

        /// <summary>
        /// HTTP response status code for this operation
        /// </summary>
        public int StatusCode { get; set; } = default!;

        /// <summary>
        /// Raw HTTP response; suitable for custom response parsing
        /// </summary>
        public HttpResponseMessage RawResponse { get; set; } = default!;

        /// <summary>
        /// The api key to use for authenticated endpoints.
        /// </summary>
        public AuthenticateResponseBody? Object { get; set; }
    }
}