
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SpeakeasyBar.Models.Requests
{
    using Newtonsoft.Json;
    
    /// <summary>
    /// The api key to use for authenticated endpoints.
    /// </summary>
    public class AuthenticateResponseBody
    {

        [JsonProperty("token")]
        public string? Token { get; set; }
    }
}