
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SpeakeasyBar.Models.Requests
{
    using SpeakeasyBar.Models.Components;
    using SpeakeasyBar.Utils;
    using System.Collections.Generic;
    
    public class CreateOrderRequest
    {

        [SpeakeasyMetadata("request:mediaType=application/json")]
        public List<OrderInput> RequestBody { get; set; } = default!;

        /// <summary>
        /// The url to call when the order is updated.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=callback_url")]
        public string? CallbackUrl { get; set; }
    }
}