
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SpeakeasyBar.Models.Requests
{
    using SpeakeasyBar.Models.Components;
    using SpeakeasyBar.Utils;
    
    public class ListDrinksRequest
    {

        /// <summary>
        /// The type of drink to filter by. If not provided all drinks will be returned.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=drinkType")]
        public DrinkType? DrinkType { get; set; }
    }
}