
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SpeakeasyBar.Models.Requests
{
    using SpeakeasyBar.Utils;
    using System.Collections.Generic;
    
    public class ListIngredientsRequest
    {

        /// <summary>
        /// A list of ingredients to filter by. If not provided all ingredients will be returned.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=false,name=ingredients")]
        public List<string>? Ingredients { get; set; }
    }
}