
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Speakeasy.Bar.Models.Callbacks
{
    using Newtonsoft.Json;
    using Speakeasy.Bar.Models.Components;
    
    public class CreateOrderOrderUpdateRequestBody
    {

        /// <summary>
        /// An order for a drink or ingredient.
        /// </summary>
        [JsonProperty("order")]
        public OrderInput? Order { get; set; }
    }
}