
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Speakeasy.Models.Shared
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class APIError
    {

        [JsonProperty("code")]
        public string? Code { get; set; }

        [JsonProperty("details")]
        public Dictionary<string, object>? Details { get; set; }

        [JsonProperty("message")]
        public string? Message { get; set; }
    }
}